language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly

env:
  - FB=2.1
  - FB=2.5

# run build against hhvm but allow them to fail
# http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

# faster builds on new travis setup not using sudo
sudo: true

# cache composer dirs
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - sudo sh -c "echo 'precedence ::ffff:0:0/96 100' >> /etc/gai.conf"
  - sudo apt-get update -qq 
  
  #installing and starting Firebird Server
  - sudo chmod +x tests/ci/travis/*.sh
  - sudo tests/ci/travis/setup_firebird${FB}.sh
  - export PATH=$PATH:/usr/local/firebird/bin

  # initialize databases
  - echo "CREATE DATABASE 'localhost:/tmp/TEST.FDB' USER 'SYSDBA' PASSWORD 'masterkey' PAGE_SIZE 16384 DEFAULT CHARACTER SET UTF8;" > /tmp/create_test.sql
  - isql-fb -i /tmp/create_test.sql
  - cat /tmp/create_test.sql

  #build pdo_firebird
  - export BRANCH=PHP-$(phpenv version-name)
  - if [[ $(phpenv version-name) == "nightly" ]]; then export BRANCH=master; fi
  - travis_retry git clone --depth=1 -b ${BRANCH} --single-branch https://github.com/php/php-src.git
  - (cd php-src/ext/pdo_firebird/; phpize && ./configure && make && sudo make install)

install:
  #enabling pdo_firebird
  - echo "extension=pdo_firebird.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - php -m | grep -i pdo

  #preparing Yii2 environment
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.1.3" --prefer-dist --no-interaction
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  #installing composer dependency
  - travis_retry composer install --prefer-dist --no-interaction
  #needed to use tests of Yii2
  - rm vendor/yiisoft/yii2-dev -Rf
  - travis_retry composer install --prefer-source -o --no-interaction

before_script:
  # show some versions and env information
  - isql-fb -z -q -i /dev/null

  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ] && [ $FB = '2.5' ]; then
      PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
    fi
script:
  - vendor/bin/phpunit --verbose $PHPUNIT_FLAGS

after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ] && [ $FB = '2.5' ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
